/**
 * 单词挑战 - 词库数据
 * 结构: 一级菜单(类别) → 二级菜单(词性) → 三级菜单(级别)
 * 每个词: { cn: 中文, py: 中文拼音, en: 英文, ipa: 英文音标, pos: 词性 }
 */

const WORD_LIBRARY = {
  "人类": {
    "动词": {
      label: "动词",
      levels: {
        "level1": {
          label: "⭐ 最常用",
          words: [
            { cn: "是", en: "be", ipa: "/biː/", pos: "v." },
            { cn: "有", en: "have", ipa: "/hæv/", pos: "v." },
            { cn: "做", en: "do", ipa: "/duː/", pos: "v." },
            { cn: "说", en: "say", ipa: "/seɪ/", pos: "v." },
            { cn: "去", en: "go", ipa: "/ɡəʊ/", pos: "v." },
            { cn: "来", en: "come", ipa: "/kʌm/", pos: "v." },
            { cn: "看", en: "see", ipa: "/siː/", pos: "v." },
            { cn: "知道", en: "know", ipa: "/nəʊ/", pos: "v." },
            { cn: "得到", en: "get", ipa: "/ɡet/", pos: "v." },
            { cn: "使", en: "make", ipa: "/meɪk/", pos: "v." },
            { cn: "想", en: "think", ipa: "/θɪŋk/", pos: "v." },
            { cn: "取", en: "take", ipa: "/teɪk/", pos: "v." },
            { cn: "看到", en: "see", ipa: "/siː/", pos: "v." },
            { cn: "知道", en: "know", ipa: "/nəʊ/", pos: "v." },
            { cn: "想要", en: "want", ipa: "/wɒnt/", pos: "v." },
            { cn: "使用", en: "use", ipa: "/juːz/", pos: "v." },
            { cn: "找到", en: "find", ipa: "/faɪnd/", pos: "v." },
            { cn: "告诉", en: "tell", ipa: "/tel/", pos: "v." },
            { cn: "工作", en: "work", ipa: "/wɜːk/", pos: "v." },
            { cn: "请求", en: "ask", ipa: "/ɑːsk/", pos: "v." },
            { cn: "尝试", en: "try", ipa: "/traɪ/", pos: "v." },
            { cn: "需要", en: "need", ipa: "/niːd/", pos: "v." },
            { cn: "成为", en: "become", ipa: "/bɪˈkʌm/", pos: "v." },
            { cn: "留下", en: "leave", ipa: "/liːv/", pos: "v." },
            { cn: "放置", en: "put", ipa: "/pʊt/", pos: "v." },
            { cn: "意味着", en: "mean", ipa: "/miːn/", pos: "v." },
            { cn: "保持", en: "keep", ipa: "/kiːp/", pos: "v." },
            { cn: "开始", en: "begin", ipa: "/bɪˈɡɪn/", pos: "v." },
            { cn: "显示", en: "show", ipa: "/ʃəʊ/", pos: "v." },
            { cn: "听到", en: "hear", ipa: "/hɪə/", pos: "v." },
            { cn: "播放", en: "play", ipa: "/pleɪ/", pos: "v." },
            { cn: "跑", en: "run", ipa: "/rʌn/", pos: "v." },
            { cn: "移动", en: "move", ipa: "/muːv/", pos: "v." },
            { cn: "生活", en: "live", ipa: "/lɪv/", pos: "v." },
            { cn: "相信", en: "believe", ipa: "/bɪˈliːv/", pos: "v." },
            { cn: "带来", en: "bring", ipa: "/brɪŋ/", pos: "v." },
            { cn: "发生", en: "happen", ipa: "/ˈhæpən/", pos: "v." },
            { cn: "写", en: "write", ipa: "/raɪt/", pos: "v." },
            { cn: "提供", en: "provide", ipa: "/prəˈvaɪd/", pos: "v." },
            { cn: "坐", en: "sit", ipa: "/sɪt/", pos: "v." },
            { cn: "站立", en: "stand", ipa: "/stænd/", pos: "v." },
            { cn: "失去", en: "lose", ipa: "/luːz/", pos: "v." },
            { cn: "支付", en: "pay", ipa: "/peɪ/", pos: "v." },
            { cn: " meeting", en: "meet", ipa: "/miːt/", pos: "v." },
            { cn: "包括", en: "include", ipa: "/ɪnˈkluːd/", pos: "v." },
            { cn: "继续", en: "continue", ipa: "/kənˈtɪnjuː/", pos: "v." },
            { cn: "设置", en: "set", ipa: "/set/", pos: "v." },
            { cn: "学习", en: "learn", ipa: "/lɜːn/", pos: "v." },
            { cn: "改变", en: "change", ipa: "/tʃeɪndʒ/", pos: "v." },
            { cn: "带领", en: "lead", ipa: "/liːd/", pos: "v." },
            { cn: "理解", en: "understand", ipa: "/ˌʌndəˈstænd/", pos: "v." },
            { cn: "观看", en: "watch", ipa: "/wɒtʃ/", pos: "v." },
            { cn: "跟随", en: "follow", ipa: "/ˈfɒləʊ/", pos: "v." },
            { cn: "停止", en: "stop", ipa: "/stɒp/", pos: "v." },
            { cn: "创造", en: "create", ipa: "/kriˈeɪt/", pos: "v." },
            { cn: "读", en: "read", ipa: "/riːd/", pos: "v." },
            { cn: "添加", en: "add", ipa: "/æd/", pos: "v." },
            { cn: "花费", en: "spend", ipa: "/spend/", pos: "v." },
            { cn: "打开", en: "open", ipa: "/ˈəʊpən/", pos: "v." },
            { cn: "行走", en: "walk", ipa: "/wɔːk/", pos: "v." },
            { cn: "赢", en: "win", ipa: "/wɪn/", pos: "v." },
            { cn: "提供", en: "offer", ipa: "/ˈɒfə/", pos: "v." },
            { cn: "记住", en: "remember", ipa: "/rɪˈmembə/", pos: "v." },
            { cn: "爱", en: "love", ipa: "/lʌv/", pos: "v." },
            { cn: "考虑", en: "consider", ipa: "/kənˈsɪdə/", pos: "v." },
            { cn: "出现", en: "appear", ipa: "/əˈpɪə/", pos: "v." },
            { cn: "买", en: "buy", ipa: "/baɪ/", pos: "v." },
            { cn: "等待", en: "wait", ipa: "/weɪt/", pos: "v." },
            { cn: "服务", en: "serve", ipa: "/sɜːv/", pos: "v." },
            { cn: "死", en: "die", ipa: "/daɪ/", pos: "v." },
            { cn: "发送", en: "send", ipa: "/send/", pos: "v." },
            { cn: "期望", en: "expect", ipa: "/ɪkˈspekt/", pos: "v." },
            { cn: "建造", en: "build", ipa: "/bɪld/", pos: "v." },
            { cn: "停留", en: "stay", ipa: "/steɪ/", pos: "v." },
            { cn: "落下", en: "fall", ipa: "/fɔːl/", pos: "v." },
            { cn: "切", en: "cut", ipa: "/kʌt/", pos: "v." },
            { cn: "达到", en: "reach", ipa: "/riːtʃ/", pos: "v." },
            { cn: "杀死", en: "kill", ipa: "/kɪl/", pos: "v." },
            { cn: "保持", en: "remain", ipa: "/rɪˈmeɪn/", pos: "v." },
            { cn: "建议", en: "suggest", ipa: "/səˈdʒest/", pos: "v." },
            { cn: "raise", en: "raise", ipa: "/reɪz/", pos: "v." },
            { cn: "通过", en: "pass", ipa: "/pɑːs/", pos: "v." },
            { cn: "销售", en: "sell", ipa: "/sel/", pos: "v." },
            { cn: "要求", en: "require", ipa: "/rɪˈkwaɪə/", pos: "v." },
            { cn: "报告", en: "report", ipa: "/rɪˈpɔːt/", pos: "v." },
            { cn: "决定", en: "decide", ipa: "/dɪˈsaɪd/", pos: "v." },
            { cn: "拉", en: "pull", ipa: "/pʊl/", pos: "v." },
            { cn: "发展", en: "develop", ipa: "/dɪˈveləp/", pos: "v." }
          ]
        },
        "level2": {
          label: "⭐⭐ 较常用",
          words: [
            { cn: "开始", en: "start", ipa: "/stɑːt/", pos: "v." },
            { cn: "记得", en: "remember", ipa: "/rɪˈmembə/", pos: "v." },
            { cn: "倾听", en: "listen", ipa: "/ˈlɪsən/", pos: "v." },
            { cn: "扔", en: "throw", ipa: "/θrəʊ/", pos: "v." },
            { cn: "掉落", en: "drop", ipa: "/drɒp/", pos: "v." },
            { cn: "吵醒", en: "wake", ipa: "/weɪk/", pos: "v." },
            { cn: "呼吸", en: "breathe", ipa: "/briːð/", pos: "v." },
            { cn: "忘记", en: "forget", ipa: "/fəˈɡet/", pos: "v." },
            { cn: "点", en: "click", ipa: "/klɪk/", pos: "v." },
            { cn: "等待", en: "wait", ipa: "/weɪt/", pos: "v." },
            { cn: "选择", en: "choose", ipa: "/tʃuːz/", pos: "v." },
            { cn: "照顾", en: "care", ipa: "/keə/", pos: "v." },
            { cn: "帮助", en: "help", ipa: "/help/", pos: "v." },
            { cn: "开始", en: "start", ipa: "/stɑːt/", pos: "v." },
            { cn: "关闭", en: "close", ipa: "/kləʊz/", pos: "v." },
            { cn: "保护", en: "protect", ipa: "/prəˈtekt/", pos: "v." },
            { cn: "影响", en: "affect", ipa: "/əˈfekt/", pos: "v." },
            { cn: "关心", en: "care", ipa: "/keə/", pos: "v." },
            { cn: "继续", en: "proceed", ipa: "/prəˈsiːd/", pos: "v." },
            { cn: "注意", en: "notice", ipa: "/ˈnəʊtɪs/", pos: "v." },
            { cn: "喜欢", en: "enjoy", ipa: "/ɪnˈdʒɔɪ/", pos: "v." },
            { cn: "检查", en: "check", ipa: "/tʃek/", pos: "v." },
            { cn: "展示", en: "display", ipa: "/dɪˈspleɪ/", pos: "v." },
            { cn: "回答", en: "answer", ipa: "/ˈɑːnsə/", pos: "v." },
            { cn: "停止", en: "quit", ipa: "/kwɪt/", pos: "v." },
            { cn: "返回", en: "return", ipa: "/rɪˈtɜːn/", pos: "v." },
            { cn: "分享", en: "share", ipa: "/ʃeə/", pos: "v." },
            { cn: "意识到", en: "realize", ipa: "/ˈrɪəlaɪz/", pos: "v." },
            { cn: "允许", en: "allow", ipa: "/əˈlaʊ/", pos: "v." },
            { cn: "介绍", en: "introduce", ipa: "/ˌɪntrəˈdjuːs/", pos: "v." },
            { cn: "讨论", en: "discuss", ipa: "/dɪˈskʌs/", pos: "v." },
            { cn: "描述", en: "describe", ipa: "/dɪˈskraɪb/", pos: "v." },
            { cn: "接受", en: "accept", ipa: "/əkˈsept/", pos: "v." },
            { cn: "成功", en: "succeed", ipa: "/səkˈsiːd/", pos: "v." },
            { cn: "微笑", en: "smile", ipa: "/smaɪl/", pos: "v." },
            { cn: "哭", en: "cry", ipa: "/kraɪ/", pos: "v." },
            { cn: "跳舞", en: "dance", ipa: "/dɑːns/", pos: "v." },
            { cn: "唱歌", en: "sing", ipa: "/sɪŋ/", pos: "v." },
            { cn: "睡觉", en: "sleep", ipa: "/sliːp/", pos: "v." },
            { cn: "醒来", en: "wake up", ipa: "/weɪk ʌp/", pos: "v." },
            { cn: "旅行", en: "travel", ipa: "/ˈtrævəl/", pos: "v." },
            { cn: "驾驶", en: "drive", ipa: "/draɪv/", pos: "v." },
            { cn: "游泳", en: "swim", ipa: "/swɪm/", pos: "v." },
            { cn: "飞", en: "fly", ipa: "/flaɪ/", pos: "v." },
            { cn: "爬", en: "climb", ipa: "/klaɪm/", pos: "v." },
            { cn: "推", en: "push", ipa: "/pʊʃ/", pos: "v." },
            { cn: "连接", en: "connect", ipa: "/kəˈnekt/", pos: "v." },
            { cn: "改变", en: "fix", ipa: "/fɪks/", pos: "v." },
            { cn: "处理", en: "handle", ipa: "/ˈhændəl/", pos: "v." },
            { cn: "包含", en: "contain", ipa: "/kənˈteɪn/", pos: "v." },
            { cn: "等待", en: "wait for", ipa: "/weɪt fɔː/", pos: "v." },
            { cn: "属于", en: "belong", ipa: "/bɪˈlɒŋ/", pos: "v." },
            { cn: "提到", en: "mention", ipa: "/ˈmenʃən/", pos: "v." },
            { cn: "处理", en: "deal", ipa: "/diːl/", pos: "v." },
            { cn: "回复", en: "reply", ipa: "/rɪˈplaɪ/", pos: "v." },
            { cn: "希望", en: "hope", ipa: "/həʊp/", pos: "v." },
            { cn: "害怕", en: "fear", ipa: "/fɪə/", pos: "v." },
            { cn: "怀疑", en: "doubt", ipa: "/daʊt/", pos: "v." },
            { cn: "计划", en: "plan", ipa: "/plæn/", pos: "v." },
            { cn: "练习", en: "practice", ipa: "/ˈpræktɪs/", pos: "v." },
            { cn: "组织", en: "organize", ipa: "/ˈɔːɡənaɪz/", pos: "v." }
          ]
        },
        "level3": {
          label: "⭐⭐⭐ 短语动词",
          words: [
            { cn: "醒来", en: "wake up", ipa: "/weɪk ʌp/", pos: "phr.v." },
            { cn: "打开(电器)", en: "turn on", ipa: "/tɜːn ɒn/", pos: "phr.v." },
            { cn: "关闭(电器)", en: "turn off", ipa: "/tɜːn ɒf/", pos: "phr.v." },
            { cn: "捡起", en: "pick up", ipa: "/pɪk ʌp/", pos: "phr.v." },
            { cn: "放弃", en: "give up", ipa: "/ɡɪv ʌp/", pos: "phr.v." },
            { cn: "继续", en: "go on", ipa: "/ɡəʊ ɒn/", pos: "phr.v." },
            { cn: "推迟", en: "put off", ipa: "/pʊt ɒf/", pos: "phr.v." },
            { cn: "查阅", en: "look up", ipa: "/lʊk ʌp/", pos: "phr.v." },
            { cn: "照顾", en: "look after", ipa: "/lʊk ˈɑːftə/", pos: "phr.v." },
            { cn: "照顾", en: "take care of", ipa: "/teɪk keə ɒv/", pos: "phr.v." },
            { cn: "发生", en: "take place", ipa: "/teɪk pleɪs/", pos: "phr.v." },
            { cn: "结果是", en: "turn out", ipa: "/tɜːn aʊt/", pos: "phr.v." },
            { cn: "提到", en: "bring up", ipa: "/brɪŋ ʌp/", pos: "phr.v." },
            { cn: "删除", en: "take away", ipa: "/teɪk əˈweɪ/", pos: "phr.v." },
            { cn: "归还", en: "give back", ipa: "/ɡɪv bæk/", pos: "phr.v." },
            { cn: "建立", en: "set up", ipa: "/set ʌp/", pos: "phr.v." },
            { cn: "查找", en: "find out", ipa: "/faɪnd aʊt/", pos: "phr.v." },
            { cn: "试穿", en: "try on", ipa: "/traɪ ɒn/", pos: "phr.v." },
            { cn: "分发", en: "hand out", ipa: "/hænd aʊt/", pos: "phr.v." },
            { cn: "归还", en: "put back", ipa: "/pʊt bæk/", pos: "phr.v." },
            { cn: "关小", en: "turn down", ipa: "/tɜːn daʊn/", pos: "phr.v." },
            { cn: "调大", en: "turn up", ipa: "/tɜːn ʌp/", pos: "phr.v." },
            { cn: "成功", en: "pull through", ipa: "/pʊl θruː/", pos: "phr.v." },
            { cn: "偿还", en: "pay back", ipa: "/peɪ bæk/", pos: "phr.v." },
            { cn: "爆发", en: "break out", ipa: "/breɪk aʊt/", pos: "phr.v." },
            { cn: "放弃", en: "let go", ipa: "/let ɡəʊ/", pos: "phr.v." },
            { cn: "偶遇", en: "run into", ipa: "/rʌn ˈɪntə/", pos: "phr.v." },
            { cn: "继续", en: "carry on", ipa: "/ˈkæri ɒn/", pos: "phr.v." },
            { cn: "查明", en: "figure out", ipa: "/ˈfɪɡə aʊt/", pos: "phr.v." },
            { cn: "拜访", en: "stop by", ipa: "/stɒp baɪ/", pos: "phr.v." },
            { cn: "拒绝", en: "turn down", ipa: "/tɜːn daʊn/", pos: "phr.v." },
            { cn: "记住", en: "keep in mind", ipa: "/kiːp ɪn maɪnd/", pos: "phr.v." },
            { cn: "推迟", en: "push back", ipa: "/pʊʃ bæk/", pos: "phr.v." },
            { cn: "处理", en: "deal with", ipa: "/diːl wɪð/", pos: "phr.v." },
            { cn: "依靠", en: "count on", ipa: "/kaʊnt ɒn/", pos: "phr.v." },
            { cn: "适应", en: "get used to", ipa: "/ɡet juːzd tuː/", pos: "phr.v." },
            { cn: "参加", en: "take part in", ipa: "/teɪk pɑːt ɪn/", pos: "phr.v." },
            { cn: "照顾", en: "look out for", ipa: "/lʊk aʊt fɔː/", pos: "phr.v." },
            { cn: "相处", en: "get along", ipa: "/ɡet əˈlɒŋ/", pos: "phr.v." },
            { cn: "坚持", en: "hold on", ipa: "/həʊld ɒn/", pos: "phr.v." },
            { cn: "查明真相", en: "find out", ipa: "/faɪnd aʊt/", pos: "phr.v." },
            { cn: "克服", en: "get over", ipa: "/ɡet ˈəʊvə/", pos: "phr.v." },
            { cn: "提出(想法)", en: "come up with", ipa: "/kʌm ʌp wɪð/", pos: "phr.v." },
            { cn: "实现", en: "carry out", ipa: "/ˈkæri aʊt/", pos: "phr.v." },
            { cn: "调查", en: "look into", ipa: "/lʊk ˈɪntə/", pos: "phr.v." },
            { cn: "拜访", en: "call on", ipa: "/kɔːl ɒn/", pos: "phr.v." },
            { cn: "取消", en: "call off", ipa: "/kɔːl ɒf/", pos: "phr.v." },
            { cn: "分解", en: "break down", ipa: "/breɪk daʊn/", pos: "phr.v." },
            { cn: "进入", en: "get into", ipa: "/ɡet ˈɪntə/", pos: "phr.v." },
            { cn: "摆脱", en: "get rid of", ipa: "/ɡet rɪd ɒv/", pos: "phr.v." },
            { cn: "练习", en: "work out", ipa: "/wɜːk aʊt/", pos: "phr.v." },
            { cn: "出现", en: "show up", ipa: "/ʃəʊ ʌp/", pos: "phr.v." },
            { cn: "关闭", en: "shut down", ipa: "/ʃʌt daʊn/", pos: "phr.v." }
          ]
        }
      }
    },
    "名词": {
      label: "名词",
      levels: {
        "level1": {
          label: "⭐ 身体部位",
          words: [
            { cn: "头", en: "head", ipa: "/hed/", pos: "n." },
            { cn: "眼睛", en: "eye", ipa: "/aɪ/", pos: "n." },
            { cn: "耳朵", en: "ear", ipa: "/ɪə/", pos: "n." },
            { cn: "鼻子", en: "nose", ipa: "/nəʊz/", pos: "n." },
            { cn: "嘴巴", en: "mouth", ipa: "/maʊθ/", pos: "n." },
            { cn: "牙齿", en: "tooth", ipa: "/tuːθ/", pos: "n." },
            { cn: "舌头", en: "tongue", ipa: "/tʌŋ/", pos: "n." },
            { cn: "嘴唇", en: "lip", ipa: "/lɪp/", pos: "n." },
            { cn: "脸", en: "face", ipa: "/feɪs/", pos: "n." },
            { cn: "脖子", en: "neck", ipa: "/nek/", pos: "n." },
            { cn: "肩膀", en: "shoulder", ipa: "/ˈʃəʊldə/", pos: "n." },
            { cn: "胳膊", en: "arm", ipa: "/ɑːm/", pos: "n." },
            { cn: "手", en: "hand", ipa: "/hænd/", pos: "n." },
            { cn: "手指", en: "finger", ipa: "/ˈfɪŋɡə/", pos: "n." },
            { cn: "胸部", en: "chest", ipa: "/tʃest/", pos: "n." },
            { cn: "肚子", en: "belly", ipa: "/ˈbeli/", pos: "n." },
            { cn: "背部", en: "back", ipa: "/bæk/", pos: "n." },
            { cn: "腰", en: "waist", ipa: "/weɪst/", pos: "n." },
            { cn: "臀部", en: "hip", ipa: "/hɪp/", pos: "n." },
            { cn: "腿", en: "leg", ipa: "/leɡ/", pos: "n." },
            { cn: "膝盖", en: "knee", ipa: "/niː/", pos: "n." },
            { cn: "脚", en: "foot", ipa: "/fʊt/", pos: "n." },
            { cn: "脚趾", en: "toe", ipa: "/təʊ/", pos: "n." },
            { cn: "脚踝", en: "ankle", ipa: "/ˈæŋkəl/", pos: "n." },
            { cn: "头发", en: "hair", ipa: "/heə/", pos: "n." },
            { cn: "眉毛", en: "eyebrow", ipa: "/ˈaɪbraʊ/", pos: "n." },
            { cn: "睫毛", en: "eyelash", ipa: "/ˈaɪlæʃ/", pos: "n." },
            { cn: "额头", en: "forehead", ipa: "/ˈfɒrɪd/", pos: "n." },
            { cn: "下巴", en: "chin", ipa: "/tʃɪn/", pos: "n." },
            { cn: "喉咙", en: "throat", ipa: "/θrəʊt/", pos: "n." },
            { cn: "锁骨", en: "collarbone", ipa: "/ˈkɒləbəʊn/", pos: "n." },
            { cn: "手肘", en: "elbow", ipa: "/ˈelbəʊ/", pos: "n." },
            { cn: "手腕", en: "wrist", ipa: "/rɪst/", pos: "n." },
            { cn: "拳头", en: "fist", ipa: "/fɪst/", pos: "n." },
            { cn: "皮肤", en: "skin", ipa: "/skɪn/", pos: "n." },
            { cn: "骨头", en: "bone", ipa: "/bəʊn/", pos: "n." },
            { cn: "肌肉", en: "muscle", ipa: "/ˈmʌsəl/", pos: "n." },
            { cn: "血管", en: "vein", ipa: "/veɪn/", pos: "n." },
            { cn: "肺", en: "lung", ipa: "/lʌŋ/", pos: "n." },
            { cn: "心脏", en: "heart", ipa: "/hɑːt/", pos: "n." },
            { cn: "胃", en: "stomach", ipa: "/ˈstʌmək/", pos: "n." },
            { cn: "肝", en: "liver", ipa: "/ˈlɪvə/", pos: "n." },
            { cn: "肾", en: "kidney", ipa: "/ˈkɪdni/", pos: "n." },
            { cn: "大脑", en: "brain", ipa: "/breɪn/", pos: "n." },
            { cn: "脊椎", en: "spine", ipa: "/spaɪn/", pos: "n." },
            { cn: "肋骨", en: "rib", ipa: "/rɪb/", pos: "n." },
            { cn: "肚脐", en: "navel", ipa: "/ˈneɪvəl/", pos: "n." },
            { cn: "脚后跟", en: "heel", ipa: "/hiːl/", pos: "n." },
            { cn: "脚底", en: "sole", ipa: "/səʊl/", pos: "n." },
            { cn: "手心", en: "palm", ipa: "/pɑːm/", pos: "n." },
            { cn: "指甲", en: "nail", ipa: "/neɪl/", pos: "n." }
          ]
        },
        "level2": {
          label: "⭐⭐ 身体局部",
          words: [
            { cn: "血液", en: "blood", ipa: "/blʌd/", pos: "n." },
            { cn: "汗液", en: "sweat", ipa: "/swet/", pos: "n." },
            { cn: "泪液", en: "tears", ipa: "/tɪəz/", pos: "n." },
            { cn: "唾液", en: "saliva", ipa: "/səˈlaɪvə/", pos: "n." },
            { cn: "尿", en: "urine", ipa: "/ˈjʊərɪn/", pos: "n." },
            { cn: "小便", en: "pee", ipa: "/piː/", pos: "n." },
            { cn: "大便", en: "poop", ipa: "/puːp/", pos: "n." },
            { cn: "屁", en: "fart", ipa: "/fɑːt/", pos: "n." },
            { cn: "皴", en: "wrinkle", ipa: "/ˈrɪŋkəl/", pos: "n." },
            { cn: "疤", en: "scar", ipa: "/skɑː/", pos: "n." },
            { cn: "痣", en: "mole", ipa: "/məʊl/", pos: "n." },
            { cn: "胎记", en: "birthmark", ipa: "/ˈbɜːθmɑːk/", pos: "n." },
            { cn: "雀斑", en: "freckle", ipa: "/ˈfrekl/", pos: "n." },
            { cn: "酒窝", en: "dimple", ipa: "/ˈdɪmpl/", pos: "n." },
            { cn: "皱纹", en: "wrinkle", ipa: "/ˈrɪŋkəl/", pos: "n." },
            { cn: "黑眼圈", en: "dark circle", ipa: "/dɑːk ˈsɜːkl/", pos: "n." },
          ]
        }
      }
    },
    "形容词/副词": {
      label: "形容词/副词",
      levels: {
        "level1": {
          label: "⭐ 感官/情感",
          words: [
            { cn: "饥饿的", en: "hungry", ipa: "/ˈhʌŋɡri/", pos: "adj." },
            { cn: "渴的", en: "thirsty", ipa: "/ˈθɜːsti/", pos: "adj." },
            { cn: "累的", en: "tired", ipa: "/ˈtaɪəd/", pos: "adj." },
            { cn: "快乐的", en: "happy", ipa: "/ˈhæpi/", pos: "adj." },
            { cn: "悲伤的", en: "sad", ipa: "/sæd/", pos: "adj." },
            { cn: "愤怒的", en: "angry", ipa: "/ˈæŋɡri/", pos: "adj." },
            { cn: "害怕的", en: "afraid", ipa: "/əˈfreɪd/", pos: "adj." },
            { cn: "惊讶的", en: "surprised", ipa: "/səˈpraɪzd/", pos: "adj." },
            { cn: "疲倦的", en: "tired", ipa: "/taɪəd/", pos: "adj." },
            { cn: "兴奋的", en: "excited", ipa: "/ɪkˈsaɪtɪd/", pos: "adj." },
            { cn: "无聊的", en: "bored", ipa: "/bɔːd/", pos: "adj." },
            { cn: "紧张的", en: "nervous", ipa: "/ˈnɜːvəs/", pos: "adj." },
            { cn: "放松的", en: "relaxed", ipa: "/rɪˈlækst/", pos: "adj." },
            { cn: "骄傲的", en: "proud", ipa: "/praʊd/", pos: "adj." },
            { cn: "害羞的", en: "shy", ipa: "/ʃaɪ/", pos: "adj." },
            { cn: "勇敢的", en: "brave", ipa: "/breɪv/", pos: "adj." },
            { cn: "害怕的", en: "scared", ipa: "/skeəd/", pos: "adj." },
            { cn: "担心的", en: "worried", ipa: "/ˈwʌrid/", pos: "adj." },
            { cn: "困惑的", en: "confused", ipa: "/kənˈfjuːzd/", pos: "adj." },
            { cn: "感激的", en: "grateful", ipa: "/ˈɡreɪtfəl/", pos: "adj." },
            { cn: "嫉妒的", en: "jealous", ipa: "/ˈdʒeləs/", pos: "adj." },
            { cn: "尴尬的", en: "embarrassed", ipa: "/ɪmˈbærəst/", pos: "adj." },
            { cn: "满足的", en: "satisfied", ipa: "/ˈsætɪsfaɪd/", pos: "adj." },
            { cn: "失望的", en: "disappointed", ipa: "/ˌdɪsəˈpɔɪntɪd/", pos: "adj." },
            { cn: "无聊的", en: "boring", ipa: "/ˈbɔːrɪŋ/", pos: "adj." },
            { cn: "有趣的", en: "interesting", ipa: "/ˈɪntrəstɪŋ/", pos: "adj." },
            { cn: "可爱的", en: "cute", ipa: "/kjuːt/", pos: "adj." },
            { cn: "漂亮的", en: "beautiful", ipa: "/ˈbjuːtɪfəl/", pos: "adj." },
            { cn: "丑陋的", en: "ugly", ipa: "/ˈʌɡli/", pos: "adj." },
            { cn: "温暖的", en: "warm", ipa: "/wɔːm/", pos: "adj." },
            { cn: "寒冷的", en: "cold", ipa: "/kəʊld/", pos: "adj." },
            { cn: "炎热的", en: "hot", ipa: "/hɒt/", pos: "adj." },
            { cn: "凉爽的", en: "cool", ipa: "/kuːl/", pos: "adj." },
            { cn: "大的", en: "big", ipa: "/bɪɡ/", pos: "adj." },
            { cn: "小的", en: "small", ipa: "/smɔːl/", pos: "adj." },
            { cn: "高的", en: "tall", ipa: "/tɔːl/", pos: "adj." },
            { cn: "矮的", en: "short", ipa: "/ʃɔːt/", pos: "adj." },
            { cn: "长的", en: "long", ipa: "/lɒŋ/", pos: "adj." },
            { cn: "短的", en: "short", ipa: "/ʃɔːt/", pos: "adj." },
            { cn: "重的", en: "heavy", ipa: "/ˈhevi/", pos: "adj." },
            { cn: "轻的", en: "light", ipa: "/laɪt/", pos: "adj." },
            { cn: "快的", en: "fast", ipa: "/fɑːst/", pos: "adj." },
            { cn: "慢的", en: "slow", ipa: "/sləʊ/", pos: "adj." },
            { cn: "新的", en: "new", ipa: "/njuː/", pos: "adj." },
            { cn: "旧的", en: "old", ipa: "/əʊld/", pos: "adj." },
            { cn: "好的", en: "good", ipa: "/ɡʊd/", pos: "adj." },
            { cn: "坏的", en: "bad", ipa: "/bæd/", pos: "adj." },
            { cn: "正确的", en: "correct", ipa: "/kəˈrekt/", pos: "adj." },
            { cn: "错误的", en: "wrong", ipa: "/rɒŋ/", pos: "adj." },
            { cn: "真的", en: "real", ipa: "/rɪəl/", pos: "adj." },
            { cn: "假的", en: "fake", ipa: "/feɪk/", pos: "adj." },
            { cn: "容易的", en: "easy", ipa: "/ˈiːzi/", pos: "adj." },
            { cn: "困难的", en: "difficult", ipa: "/ˈdɪfɪkəlt/", pos: "adj." }
          ]
        },
        "level2": {
          label: "⭐⭐ 描述人的",
          words: [
            { cn: "善良的", en: "kind", ipa: "/kaɪnd/", pos: "adj." },
            { cn: "邪恶的", en: "evil", ipa: "/ˈiːvəl/", pos: "adj." },
            { cn: "健康的", en: "healthy", ipa: "/ˈhelθi/", pos: "adj." },
            { cn: "聪明的", en: "smart", ipa: "/smɑːt/", pos: "adj." },
            { cn: "愚蠢的", en: "stupid", ipa: "/ˈstjuːpɪd/", pos: "adj." },
            { cn: "勤奋的", en: "hardworking", ipa: "/ˈhɑːdwɜːkɪŋ/", pos: "adj." },
            { cn: "懒惰的", en: "lazy", ipa: "/ˈleɪzi/", pos: "adj." },
            { cn: "诚实的", en: "honest", ipa: "/ˈɒnɪst/", pos: "adj." },
            { cn: "说谎的", en: "lying", ipa: "/ˈlaɪɪŋ/", pos: "adj." },
            { cn: "友好的", en: "friendly", ipa: "/ˈfrendli/", pos: "adj." },
            { cn: "粗鲁的", en: "rude", ipa: "/ruːd/", pos: "adj." },
            { cn: "有耐心的", en: "patient", ipa: "/ˈpeɪʃənt/", pos: "adj." },
            { cn: "急躁的", en: "impatient", ipa: "/ɪmˈpeɪʃənt/", pos: "adj." },
            { cn: "慷慨的", en: "generous", ipa: "/ˈdʒenərəs/", pos: "adj." },
            { cn: "吝啬的", en: "stingy", ipa: "/ˈstɪndʒi/", pos: "adj." },
            { cn: "温柔的", en: "gentle", ipa: "/ˈdʒentəl/", pos: "adj." },
            { cn: "粗暴的", en: "rough", ipa: "/rʌf/", pos: "adj." },
            { cn: "幽默的", en: "humorous", ipa: "/ˈhjuːmərəs/", pos: "adj." },
            { cn: "严肃的", en: "serious", ipa: "/ˈsɪəriəs/", pos: "adj." },
            { cn: "外向的", en: "outgoing", ipa: "/ˈaʊtɡəʊɪŋ/", pos: "adj." },
            { cn: "内向的", en: "introverted", ipa: "/ˈɪntrəvɜːtɪd/", pos: "adj." },
            { cn: "自信的", en: "confident", ipa: "/ˈkɒnfɪdənt/", pos: "adj." },
            { cn: "胆小的", en: "timid", ipa: "/ˈtɪmɪd/", pos: "adj." },
            { cn: "有才华的", en: "talented", ipa: "/ˈtæləntɪd/", pos: "adj." },
            { cn: "有创造力的", en: "creative", ipa: "/kriˈeɪtɪv/", pos: "adj." },
            { cn: "可靠的", en: "reliable", ipa: "/rɪˈlaɪəbəl/", pos: "adj." },
            { cn: "不可靠的", en: "unreliable", ipa: "/ˌʌnrɪˈlaɪəbəl/", pos: "adj." },
            { cn: "有责任心的", en: "responsible", ipa: "/rɪˈspɒnsɪbəl/", pos: "adj." },
            { cn: "自私的", en: "selfish", ipa: "/ˈselfɪʃ/", pos: "adj." },
            { cn: "无私的", en: "selfless", ipa: "/ˈselfləs/", pos: "adj." },
            { cn: "有礼貌的", en: "polite", ipa: "/pəˈlaɪt/", pos: "adj." },
            { cn: "无礼的", en: "impolite", ipa: "/ˌɪmpəˈlaɪt/", pos: "adj." },
            { cn: "乐观的", en: "optimistic", ipa: "/ˌɒptɪˈmɪstɪk/", pos: "adj." },
            { cn: "悲观的", en: "pessimistic", ipa: "/ˌpesɪˈmɪstɪk/", pos: "adj." },
            { cn: "有同情心的", en: "compassionate", ipa: "/kəmˈpæʃənət/", pos: "adj." },
            { cn: "冷漠的", en: "indifferent", ipa: "/ɪnˈdɪfərənt/", pos: "adj." },
            { cn: "有魅力的", en: "charming", ipa: "/ˈtʃɑːmɪŋ/", pos: "adj." },
            { cn: "有吸引力的", en: "attractive", ipa: "/əˈtræktɪv/", pos: "adj." },
            { cn: "英俊的", en: "handsome", ipa: "/ˈhænsəm/", pos: "adj." },
            { cn: "优雅的", en: "elegant", ipa: "/ˈelɪɡənt/", pos: "adj." },
            { cn: "强壮的", en: "strong", ipa: "/strɒŋ/", pos: "adj." },
            { cn: "虚弱的", en: "weak", ipa: "/wiːk/", pos: "adj." },
            { cn: "健康的", en: "healthy", ipa: "/ˈhelθi/", pos: "adj." },
            { cn: "生病的", en: "sick", ipa: "/sɪk/", pos: "adj." },
            { cn: "富有的", en: "rich", ipa: "/rɪtʃ/", pos: "adj." },
            { cn: "贫穷的", en: "poor", ipa: "/pɔː/", pos: "adj." },
            { cn: "有名的", en: "famous", ipa: "/ˈfeɪməs/", pos: "adj." },
            { cn: "无名的", en: "unknown", ipa: "/ˌʌnˈnəʊn/", pos: "adj." },
            { cn: "重要的", en: "important", ipa: "/ɪmˈpɔːtənt/", pos: "adj." },
            { cn: "不重要的", en: "unimportant", ipa: "/ˌʌnɪmˈpɔːtənt/", pos: "adj." },
            { cn: "安全的", en: "safe", ipa: "/seɪf/", pos: "adj." },
            { cn: "危险的", en: "dangerous", ipa: "/ˈdeɪndʒərəs/", pos: "adj." },
            { cn: "安静的", en: "quiet", ipa: "/ˈkwaɪət/", pos: "adj." },
            { cn: "吵闹的", en: "noisy", ipa: "/ˈnɔɪzi/", pos: "adj." }
          ]
        },
        "level3": {
          label: "⭐⭐⭐ 常见副词",
          words: [
            { cn: "快速地", en: "quickly", ipa: "/ˈkwɪkli/", pos: "adv." },
            { cn: "缓慢地", en: "slowly", ipa: "/ˈsləʊmli/", pos: "adv." },
            { cn: "安静地", en: "quietly", ipa: "/ˈkwaɪətli/", pos: "adv." },
            { cn: "大声地", en: "loudly", ipa: "/ˈlaʊdli/", pos: "adv." },
            { cn: "仔细地", en: "carefully", ipa: "/ˈkeəfəli/", pos: "adv." },
            { cn: "粗心地", en: "carelessly", ipa: "/ˈkeələsli/", pos: "adv." },
            { cn: "小心地", en: "carefully", ipa: "/ˈkeəfəli/", pos: "adv." },
            { cn: "认真地", en: "seriously", ipa: "/ˈsɪəriəsli/", pos: "adv." },
            { cn: "努力地", en: "hard", ipa: "/hɑːd/", pos: "adv." },
            { cn: "容易地", en: "easily", ipa: "/ˈiːzɪli/", pos: "adv." },
            { cn: "困难地", en: "difficultly", ipa: "/ˈdɪfɪkəltli/", pos: "adv." },
            { cn: "经常", en: "often", ipa: "/ˈɒfən/", pos: "adv." },
            { cn: "总是", en: "always", ipa: "/ˈɔːlweɪz/", pos: "adv." },
            { cn: "从不", en: "never", ipa: "/ˈnevə/", pos: "adv." },
            { cn: "有时", en: "sometimes", ipa: "/ˈsʌmtaɪmz/", pos: "adv." },
            { cn: "通常", en: "usually", ipa: "/ˈjuːʒuəli/", pos: "adv." },
            { cn: "已经", en: "already", ipa: "/ɔːlˈredi/", pos: "adv." },
            { cn: "仍然", en: "still", ipa: "/stɪl/", pos: "adv." },
            { cn: "只是", en: "just", ipa: "/dʒʌst/", pos: "adv." },
            { cn: "几乎", en: "almost", ipa: "/ˈɔːlməʊst/", pos: "adv." },
            { cn: "完全", en: "completely", ipa: "/kəmˈpliːtli/", pos: "adv." },
            { cn: "真正地", en: "truly", ipa: "/ˈtruːli/", pos: "adv." },
            { cn: "特别", en: "especially", ipa: "/ɪˈspeʃəli/", pos: "adv." },
            { cn: "大概", en: "probably", ipa: "/ˈprɒbəbli/", pos: "adv." },
            { cn: "肯定", en: "definitely", ipa: "/ˈdefɪnətli/", pos: "adv." },
            { cn: "也许", en: "maybe", ipa: "/ˈmeɪbi/", pos: "adv." },
            { cn: "可能", en: "possibly", ipa: "/ˈpɒsəbli/", pos: "adv." },
            { cn: "相当", en: "quite", ipa: "/kwaɪt/", pos: "adv." },
            { cn: "非常", en: "very", ipa: "/ˈveri/", pos: "adv." },
            { cn: "太", en: "too", ipa: "/tuː/", pos: "adv." },
            { cn: "足够", en: "enough", ipa: "/ɪˈnʌf/", pos: "adv." },
            { cn: "如此", en: "so", ipa: "/səʊ/", pos: "adv." },
            { cn: "那么", en: "then", ipa: "/ðen/", pos: "adv." },
            { cn: "现在", en: "now", ipa: "/naʊ/", pos: "adv." },
            { cn: "立刻", en: "immediately", ipa: "/ɪˈmiːdiətli/", pos: "adv." },
            { cn: "很快", en: "quickly", ipa: "/ˈkwɪkli/", pos: "adv." },
            { cn: "慢慢地", en: "slowly", ipa: "/ˈsləʊmli/", pos: "adv." },
            { cn: "突然", en: "suddenly", ipa: "/ˈsʌdənli/", pos: "adv." },
            { cn: "幸运地", en: "luckily", ipa: "/ˈlʌkɪli/", pos: "adv." },
            { cn: "不幸地", en: "unfortunately", ipa: "/ʌnˈfɔːtʃənətli/", pos: "adv." },
            { cn: "相反", en: "instead", ipa: "/ɪnˈsted/", pos: "adv." },
            { cn: "此外", en: "besides", ipa: "/bɪˈsaɪdz/", pos: "adv." },
            { cn: "然而", en: "however", ipa: "/haʊˈevə/", pos: "adv." },
            { cn: "因此", en: "therefore", ipa: "/ˈðeəfɔː/", pos: "adv." },
            { cn: "也", en: "also", ipa: "/ˈɔːlsəʊ/", pos: "adv." },
            { cn: "甚至", en: "even", ipa: "/ˈiːvən/", pos: "adv." },
            { cn: "仅仅", en: "merely", ipa: "/ˈmɪəli/", pos: "adv." },
            { cn: "实际上", en: "actually", ipa: "/ˈæktʃuəli/", pos: "adv." },
            { cn: "显然", en: "obviously", ipa: "/ˈɒbviəsli/", pos: "adv." },
            { cn: "自然地", en: "naturally", ipa: "/ˈnætʃrəli/", pos: "adv." },
            { cn: "简单地", en: "simply", ipa: "/ˈsɪmpli/", pos: "adv." }
          ]
        }
      }
    }
  },
  "字母个数": {
    "三个字母": {
      label: "三个字母",
      levels: {
        "level1": {
          label: "⭐ 常见词汇",
          words: [
            { cn: "坏的", en: "bad", ipa: "/bæd/", pos: "adj." },
            { cn: "包，袋子", en: "bag", ipa: "/bæɡ/", pos: "n." },
            { cn: "蝙蝠；球拍", en: "bat", ipa: "/bæt/", pos: "n." },
            { cn: "床", en: "bed", ipa: "/bed/", pos: "n." },
            { cn: "大的", en: "big", ipa: "/bɪɡ/", pos: "adj." },
            { cn: "箱子；容器", en: "bin", ipa: "/bɪn/", pos: "n." },
            { cn: "一点；小块", en: "bit", ipa: "/bɪt/", pos: "n." },
            { cn: "盒子", en: "box", ipa: "/bɒks/", pos: "n." },
            { cn: "虫子；故障", en: "bug", ipa: "/bʌɡ/", pos: "n." },
            { cn: "能；罐头", en: "can", ipa: "/kæn/", pos: "v./n." },
            { cn: "帽子", en: "cap", ipa: "/kæp/", pos: "n." },
            { cn: "猫", en: "cat", ipa: "/kæt/", pos: "n." },
            { cn: "杯子", en: "cup", ipa: "/kʌp/", pos: "n." },
            { cn: "爸爸", en: "dad", ipa: "/dæd/", pos: "n." },
            { cn: "兽穴；洞穴", en: "den", ipa: "/den/", pos: "n." },
            { cn: "挖；掘", en: "dig", ipa: "/dɪɡ/", pos: "v." },
            { cn: "狗", en: "dog", ipa: "/dɒɡ/", pos: "n." },
            { cn: "点；小圆点", en: "dot", ipa: "/dɒt/", pos: "n." },
            { cn: "风扇", en: "fan", ipa: "/fæn/", pos: "n." },
            { cn: "胖的", en: "fat", ipa: "/fæt/", pos: "adj." },
            { cn: "喂养（feed 过去式）", en: "fed", ipa: "/fed/", pos: "v." },
            { cn: "无花果", en: "fig", ipa: "/fɪɡ/", pos: "n." },
            { cn: "适合；合身", en: "fit", ipa: "/fɪt/", pos: "v./adj." },
            { cn: "狐狸", en: "fox", ipa: "/fɒks/", pos: "n." },
            { cn: "缺口；缝隙", en: "gap", ipa: "/ɡæp/", pos: "n." },
            { cn: "气体；煤气", en: "gas", ipa: "/ɡæs/", pos: "n." },
            { cn: "得到", en: "get", ipa: "/ɡet/", pos: "v." },
            { cn: "枪", en: "gun", ipa: "/ɡʌn/", pos: "n." },
            { cn: "火腿", en: "ham", ipa: "/hæm/", pos: "n." },
            { cn: "帽子", en: "hat", ipa: "/hæt/", pos: "n." },
            { cn: "母鸡", en: "hen", ipa: "/hen/", pos: "n." },
            { cn: "臀部", en: "hip", ipa: "/hɪp/", pos: "n." },
            { cn: "击打；碰撞", en: "hit", ipa: "/hɪt/", pos: "v./n." },
            { cn: "公猪", en: "hog", ipa: "/hɒɡ/", pos: "n." },
            { cn: "单脚跳", en: "hop", ipa: "/hɒp/", pos: "v." },
            { cn: "热的", en: "hot", ipa: "/hɒt/", pos: "adj." },
            { cn: "果酱", en: "jam", ipa: "/dʒæm/", pos: "n." },
            { cn: "喷气式飞机", en: "jet", ipa: "/dʒet/", pos: "n." },
            { cn: "小孩", en: "kid", ipa: "/kɪd/", pos: "n." },
            { cn: "成套工具", en: "kit", ipa: "/kɪt/", pos: "n." },
            { cn: "腿", en: "leg", ipa: "/leɡ/", pos: "n." },
            { cn: "盖子", en: "lid", ipa: "/lɪd/", pos: "n." },
            { cn: "原木；木头", en: "log", ipa: "/lɒɡ/", pos: "n." },
            { cn: "男人；人类", en: "man", ipa: "/mæn/", pos: "n." },
            { cn: "地图", en: "map", ipa: "/mæp/", pos: "n." },
            { cn: "垫子", en: "mat", ipa: "/mæt/", pos: "n." },
            { cn: "男人们", en: "men", ipa: "/men/", pos: "n." },
            { cn: "遇见（meet 过去式）", en: "met", ipa: "/met/", pos: "v." },
            { cn: "泥；泥浆", en: "mud", ipa: "/mʌd/", pos: "n." },
            { cn: "网", en: "net", ipa: "/net/", pos: "n." },
            { cn: "坚果", en: "nut", ipa: "/nʌt/", pos: "n." },
            { cn: "平底锅", en: "pan", ipa: "/pæn/", pos: "n." },
            { cn: "钢笔", en: "pen", ipa: "/pen/", pos: "n." },
            { cn: "宠物", en: "pet", ipa: "/pet/", pos: "n." },
            { cn: "猪", en: "pig", ipa: "/pɪɡ/", pos: "n." },
            { cn: "大头针；别针", en: "pin", ipa: "/pɪn/", pos: "n." },
            { cn: "锅；壶", en: "pot", ipa: "/pɒt/", pos: "n." },
            { cn: "敲击；说唱", en: "rap", ipa: "/ræp/", pos: "v./n." },
            { cn: "红色的", en: "red", ipa: "/red/", pos: "adj." },
            { cn: "肋骨", en: "rib", ipa: "/rɪb/", pos: "n." },
            { cn: "边缘；边框", en: "rim", ipa: "/rɪm/", pos: "n." },
            { cn: "杆；棒", en: "rod", ipa: "/rɒd/", pos: "n." },
            { cn: "腐烂", en: "rot", ipa: "/rɒt/", pos: "v." },
            { cn: "小地毯", en: "rug", ipa: "/rʌɡ/", pos: "n." },
            { cn: "伤心的", en: "sad", ipa: "/sæd/", pos: "adj." },
            { cn: "坐（sit 过去式）", en: "sat", ipa: "/sæt/", pos: "v." },
            { cn: "放置；设置", en: "set", ipa: "/set/", pos: "v." },
            { cn: "小口喝", en: "sip", ipa: "/sɪp/", pos: "v." },
            { cn: "坐", en: "sit", ipa: "/sɪt/", pos: "v." },
            { cn: "儿子", en: "son", ipa: "/sʌn/", pos: "n." },
            { cn: "太阳", en: "sun", ipa: "/sʌn/", pos: "n." },
            { cn: "标签", en: "tag", ipa: "/tæɡ/", pos: "n." },
            { cn: "棕褐色", en: "tan", ipa: "/tæn/", pos: "adj./n." },
            { cn: "轻拍", en: "tap", ipa: "/tæp/", pos: "v./n." },
            { cn: "十", en: "ten", ipa: "/ten/", pos: "num." },
            { cn: "尖端；小费", en: "tip", ipa: "/tɪp/", pos: "n." },
            { cn: "浴盆", en: "tub", ipa: "/tʌb/", pos: "n." },
            { cn: "厢式货车", en: "van", ipa: "/væn/", pos: "n." },
            { cn: "兽医", en: "vet", ipa: "/vet/", pos: "n." },
            { cn: "摇摆；摆动", en: "wag", ipa: "/wæɡ/", pos: "v." },
            { cn: "网", en: "web", ipa: "/web/", pos: "n." },
            { cn: "湿的", en: "wet", ipa: "/wet/", pos: "adj." },
            { cn: "赢", en: "win", ipa: "/wɪn/", pos: "v." },
            { cn: "智慧；智力", en: "wit", ipa: "/wɪt/", pos: "n." },
            { cn: "拉链", en: "zip", ipa: "/zɪp/", pos: "n." }

          ]
        }
      }
    }
  }
};

// 导出词库
if (typeof module !== 'undefined' && module.exports) {
  module.exports = WORD_LIBRARY;
}
